import * as path from 'path';
import * as fs from 'fs-extra';
import ejs from 'ejs';
import { ProjectConfig } from '../config/types';
import chalk from 'chalk';
import * as prettier from 'prettier';
import { getDependencies } from './dependencies';

export async function generateProject(config: ProjectConfig) {
  const isCurrentDir = config.projectName === '.';
  const targetDir = isCurrentDir ? process.cwd() : path.join(process.cwd(), config.projectName);

  if (!isCurrentDir && fs.existsSync(targetDir)) {
    throw new Error(`Directory ${targetDir} already exists.`);
  }

  if (isCurrentDir) {
    config.projectName = path.basename(process.cwd());
  }

  // Create project directory
  await fs.ensureDir(targetDir);

  const templatesDir = path.join(__dirname, '../../templates');
  
  // 1. Copy common templates
  await copyTemplateFiles(path.join(templatesDir, 'common'), targetDir, config);
  
  // 2. Language templates
  await copyTemplateFiles(path.join(templatesDir, `language/${config.language}`), targetDir, config);
  
  // 3. Framework templates
  await copyTemplateFiles(path.join(templatesDir, `framework/${config.framework}`), targetDir, config);
  
  // 3.5. Structure templates
  // The core architectural components (ApiError, validation, constants, response handlers)
  // are shared across all structures in architecture/common.
  await copyTemplateFiles(path.join(templatesDir, 'architecture/common'), targetDir, config);
  
  if (config.structure === 'enterprise') {
    // Remove the basic controller generated by the framework
    const basicControllerPath = path.join(targetDir, 'src/controllers/index.ts');
    if (fs.existsSync(basicControllerPath)) {
      await fs.remove(basicControllerPath);
    }
    await copyTemplateFiles(path.join(templatesDir, 'architecture/enterprise'), targetDir, config);
  }
  
  // 4. Database common templates
  if (config.database !== 'none') {
    await copyTemplateFiles(path.join(templatesDir, `database/common`), targetDir, config);
  }

  // 5. ORM templates
  if (config.orm !== 'none') {
    await copyTemplateFiles(path.join(templatesDir, `orm/${config.orm}`), targetDir, config);
  }

  // 6. Auth templates
  if (config.authentication !== 'none') {
    await copyTemplateFiles(path.join(templatesDir, `auth/${config.authentication}`), targetDir, config);
    if (config.authentication === 'jwt' && config.structure === 'simple') {
      await fs.remove(path.join(targetDir, 'src/services/auth'));
      // Remove empty services dir if no other services exist
      try {
        const servicesDir = path.join(targetDir, 'src/services');
        if ((await fs.readdir(servicesDir)).length === 0) {
          await fs.remove(servicesDir);
        }
      } catch (e) {}
    }
  }

  // 7. Testing templates
  if (config.testingFramework !== 'none') {
    await copyTemplateFiles(path.join(templatesDir, `testing/${config.testingFramework}`), targetDir, config);
  }

  // 8. Docker templates
  if (config.docker) {
    await copyTemplateFiles(path.join(templatesDir, 'features/docker'), targetDir, config);
  }

  // 7.2 Redis templates
  if (config.redis) {
    await copyTemplateFiles(path.join(templatesDir, `features/redis`), targetDir, config);
  }

  // 7.3 Swagger templates
  if (config.swagger) {
    await copyTemplateFiles(path.join(templatesDir, `features/swagger`), targetDir, config);
  }

  // 7.5 Copy .env.example to .env
  if (fs.existsSync(path.join(targetDir, '.env.example'))) {
    await fs.copy(path.join(targetDir, '.env.example'), path.join(targetDir, '.env'));
  }

  // 8. Generate package.json
  await generatePackageJson(targetDir, config);

  console.log(chalk.green(`\nSuccessfully created project ${config.projectName}!`));
  console.log(`\nNext steps:`);
  console.log(`  cd ${config.projectName}`);
  console.log(`  ${config.packageManager} install`);
  console.log(`  ${config.packageManager} run dev`);
}

async function copyTemplateFiles(source: string, target: string, config: ProjectConfig) {
  if (!fs.existsSync(source)) return;
  
  const files = await fs.readdir(source);
  for (const file of files) {
    const srcPath = path.join(source, file);
    
    // In templates, directories mapping to `src` should merge, not overwrite.
    // EJS templates usually have `.ejs` extension.
    let destFileName = file.endsWith('.ejs') ? file.replace('.ejs', '') : file;
    
    // Evaluate dynamic file names using EJS
    if (destFileName.includes('<%=')) {
      destFileName = ejs.render(destFileName, config);
    }
    
    const destPath = path.join(target, destFileName);
    
    const stat = await fs.stat(srcPath);
    if (stat.isDirectory()) {
      await fs.ensureDir(destPath);
      await copyTemplateFiles(srcPath, destPath, config);
    } else {
      if (file.endsWith('.ejs')) {
        const content = await fs.readFile(srcPath, 'utf8');
        let rendered = ejs.render(content, config);
        // Clean up excessive newlines caused by EJS template tags
        rendered = rendered.replace(/\n\s*\n\s*\n/g, '\n\n');
        
        if (destFileName.endsWith('.ts') || destFileName.endsWith('.js')) {
          try {
            rendered = await prettier.format(rendered, {
              parser: destFileName.endsWith('.ts') ? 'typescript' : 'babel',
              singleQuote: true,
              trailingComma: 'all',
              printWidth: 100,
            });
          } catch (e) {
            // fallback if format fails
          }
        }
        
        await fs.writeFile(destPath, rendered);
      } else {
        await fs.copy(srcPath, destPath, { overwrite: true });
      }
    }
  }
}

async function generatePackageJson(targetDir: string, config: ProjectConfig) {
  const deps = getDependencies(config);
  
  const packageJson = {
    name: config.projectName,
    version: '1.0.0',
    description: 'Backend API generated with buildmyapp',
    main: config.language === 'typescript' ? 'dist/index.js' : 'src/index.js',
    scripts: {
      dev: config.language === 'typescript' ? 'ts-node src/index.ts' : 'nodemon src/index.js',
      build: config.language === 'typescript' ? 'tsc' : 'echo "No build step required"',
      start: 'node dist/index.js',
      lint: config.language === 'typescript' ? 'eslint src --ext .ts' : 'eslint src --ext .js',
      'lint:fix': config.language === 'typescript' ? 'eslint src --ext .ts --fix' : 'eslint src --ext .js --fix',
      ...(config.testingFramework === 'jest' ? {
        'test': 'jest'
      } : config.testingFramework === 'mocha' ? {
        'test': config.language === 'typescript' ? 'mocha -r ts-node/register tests/**/*.test.ts' : 'mocha tests/**/*.test.js'
      } : {
        'test': 'echo "Error: no test specified" && exit 1'
      }),
      ...(config.orm === 'sequelize' ? {
        'migrate': 'sequelize-cli db:migrate',
        'migrate:undo': 'sequelize-cli db:migrate:undo',
        'db:seed': 'sequelize-cli db:seed:all'
      } : {}),
      ...(config.orm === 'prisma' ? {
        'migrate': 'prisma migrate dev',
        'db:seed': 'prisma db seed'
      } : {}),
      ...(config.orm === 'mongoose' ? {
        'db:seed': config.language === 'typescript' ? 'ts-node src/scripts/seed.ts' : 'node src/scripts/seed.js'
      } : {}),
      'prepare': 'husky'
    },
    ...(config.orm === 'prisma' ? {
      'prisma': {
        'seed': config.language === 'typescript' ? 'ts-node prisma/seed.ts' : 'node prisma/seed.js'
      }
    } : {}),
    'lint-staged': {
      'src/**/*.{js,ts}': [
        'eslint --fix'
      ]
    },
    dependencies: deps.dependencies,
    devDependencies: deps.devDependencies
  };

  await fs.writeJSON(path.join(targetDir, 'package.json'), packageJson, { spaces: 2 });
}
